spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/quartz?characterEncoding=utf-8&useSSL=false
      username: root
      password: root
  jpa:
      hibernate:
  #            ddl-auto: none
          ddl-auto: update

      properties:
          hibernate.globally_quoted_identifiers: true
          hibernate.show_sql: false
          hibernate.format_sql: true

scheduler:
    quartz:
      enabled: true
      schedulerName: Quartztest
      overwriteExistingJobs: true

job:
  cron:
      upperRepeatNotifyJob: 0/10 * * * * ?
      middleRepeatNotifyJob: 0/30 * * * * ?


